version: '3.8'

networks:
  app:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  order:
    container_name: app
    networks:
      - app
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    container_name: app-postgres
    networks:
      - app
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=order_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: app-pgadmin
    networks:
      - app
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8888:80"
    restart: unless-stopped